CREATE DATABASE IF NOT EXISTS piano;
USE piano;

CREATE TABLE IF NOT EXISTS Usuarios (
    ID_Usuario INT AUTO_INCREMENT PRIMARY KEY,
    Usuario VARCHAR(50) UNIQUE NOT NULL,
    Contraseña VARCHAR(50) NOT NULL,
    Correo VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Canciones () {
    ID_Cancion INT AUTO_INCREMENT PRIMARY KEY,
    Titulo VARCHAR(50) NOT NULL,
    Fecha_Hora DATETIME NOT NULL
}

CREATE TABLE IF NOT EXISTS Notas () {
    ID_Nota INT AUTO_INCREMENT PRIMARY KEY,
    Nota VARCHAR(3) NOT NULL,
    Cifrado CHAR(1) NOT NULL
};

CREATE TABLE IF NOT EXISTS Partituras () {
    ID_Partitura INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (ID_Cancion) REFERENCES Canciones(ID_Cancion),
    FOREIGN KEY (ID_Nota) REFERENCES Notas(ID_Nota),
    Orden INT NOT NULL
};